##### create report
POST http://localhost:3000/reports
Content-Type: application/json

{
    "price": 20000,
    "make": "Toyota",
    "model": "Corolla",
    "year": 2010,
    "mileage": 150000,
    "lng": 0,
    "lat": 0
}

##### get report by id
PATCH  http://localhost:3000/reports/9
Content-Type: application/json

{
   "approved":false
}


### get Estimate
GET http://localhost:3000/reports?make=Toyota&model=Corolla&year=2010&lng=0&lat=0&mileage=150000